name: Run CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Use Node.js version v16
        uses: actions/setup-node@v2
        with:
          node-version: 16.16.0
      - run: |
          npm run install
          npm run build --prefix client
